"use client";

import React from "react";

/**
 * @deprecated This provider is now a pass-through.
 * The theme system has been centralized in src/lib/theme-config.ts
 * Colors are now managed via CSS variables generated by `npm run theme:generate`
 */
export const DesignSystemProvider: React.FC<{ children: React.ReactNode; defaultTheme?: string }> = ({
  children,
}) => {
  return <>{children}</>;
};

/**
 * @deprecated Use the theme-config.ts system instead.
 * To change themes, edit `currentTheme` in src/lib/theme-config.ts
 */
export const ThemeSwitcher = () => {
  return (
    <div className="text-xs text-muted-foreground">
      Theme switching is now managed via theme-config.ts
    </div>
  );
};
